CREATE USER C##BENJAMIN_BAEZA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##BENJAMIN_BAEZA;

CREATE USER C##CAMILO_BAZAN IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##CAMILO_BAZAN;

CREATE USER C##MAURICIO_BUSTAMANTE IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##MAURICIO_BUSTAMANTE;

CREATE USER C##NICOLAS_CAROCA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##NICOLAS_CAROCA;

CREATE USER C##MILLARAY_CARRASCO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##MILLARAY_CARRASCO;

CREATE USER C##YOSHUA_CASTILLO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##YOSHUA_CASTILLO;

CREATE USER C##VICENTE_CAYUQUEO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##VICENTE_CAYUQUEO;

CREATE USER C##BAYRON_CID IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##BAYRON_CID;

CREATE USER C##MATIAS_DIAZ IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##MATIAS_DIAZ;

CREATE USER C##PIA_GARCIA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##PIA_GARCIA;

CREATE USER C##FELIPE_HUMAR IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##FELIPE_HUMAR;

CREATE USER C##BENJAMIN_LEIVA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##BENJAMIN_LEIVA;

CREATE USER C##MAYTHEM_MALDONADO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##MAYTHEM_MALDONADO;

CREATE USER C##JAIRO_MALDONADO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##JAIRO_MALDONADO;

CREATE USER C##DANTE_PARDO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##DANTE_PARDO;

CREATE USER C##CESAR_RIOS IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##CESAR_RIOS;

CREATE USER C##MATIAS_ROJAS IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##MATIAS_ROJAS;

CREATE USER C##CHRISTOPHER_RUIZ IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##CHRISTOPHER_RUIZ;

CREATE USER C##VICENTE_SAGREDO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##VICENTE_SAGREDO;

CREATE USER C##VICENTE_SEPULVEDA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##VICENTE_SEPULVEDA;

CREATE USER C##ABRAHAM_SILVA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##ABRAHAM_SILVA;

CREATE USER C##EDUARDO_SANCHEZ IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##EDUARDO_SANCHEZ;

CREATE USER C##MARTIN_TAPIA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##MARTIN_TAPIA;

CREATE USER C##JAMINTHON_TORRES IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##JAMINTHON_TORRES;

CREATE USER C##SEBASTIAN_URRUTIA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##SEBASTIAN_URRUTIA;

CREATE USER C##MAXIMO_VALDES IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##MAXIMO_VALDES;

CREATE USER C##CARLOS_YANEZ IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##CARLOS_YANEZ;

CREATE USER C##ANGELO_ZAMORA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##ANGELO_ZAMORA;

CREATE USER C##SEBASTIAN_MORALES IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##SEBASTIAN_MORALES;