CREATE TABLE USERS (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(50) UNIQUE,
    password_hash VARCHAR2(200)
);

CREATE TABLE INDICADORES (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    fecha_indicador DATE,
    valor NUMBER,
    fecha_consulta DATE,
    usuario VARCHAR2(50),
    fuente VARCHAR2(100)
);
